### ISSUE TITLE
Not showing element in material ui dialog

### ISSUE THREAD

**Issue by nlafleur** [usablica/intro.js#1085]
## Description
Whenever I have a steps element with the class lets say step2 which is inside a material ui dialog it does not highlight the dom element.

I believe that this has something to do with the zIndexes and the way the dialog is build.
![image](https://user-images.githubusercontent.com/40174298/100203209-961f3600-2f02-11eb-8b88-06fa19213c00.png)

## Expected Behavior
I created this in photoshop but the highlight should be pointing to the dialogActions aswel...
![image](https://user-images.githubusercontent.com/40174298/100201692-a2a28f00-2f00-11eb-85cd-abeb37175304.png)
It is supposed to highlight the actionButtons 

## Actual Behavior
What actually happened?
![image](https://user-images.githubusercontent.com/40174298/100201774-bc43d680-2f00-11eb-9669-5b718637eb01.png)

## Example (recommended)
The intro.js config:
steps array
```
steps: [
  {
    element: ".step1",
    intro: "<div><h3>Stap1</h3>Klik op één van de punten op de kaart voor meer informatie over deze locatie.</div>",
    tooltipClass: "mijnHoogwaterstanden-tooltip"
  },
  {
    element: ".step2",
    intro: "<div><h3>Stap2</h3>Gebruik de onderstaande pijlen om te navigeren door dit dialoog en klik op 'OK' om deze te sluiten.</div>",
    tooltipClass: "mijnHoogwaterstanden-tooltip"
  }
]
```

The mobile stepper inside the <Dialog />
```
<div className="step2" style={{ width: "100%" }}>
  <MobileStepper
    id='stepper'
    steps={dialog && dialog.containers.length}
    position="static"
    activeStep={activeDialogs[dialog.key]}
    className={classes.mobileStepper}
    backButton={
      <Button className={classes.button} onClick={() => this.handleStep(dialog, 'back')} disabled={activeDialogs[dialog.key] ? activeDialogs[dialog.key] === 0 : true}>
        <ChevronLeft />
        {stepper && stepper.offsetWidth >= 320 ? previous : null}
      </Button>
    }
    nextButton={
      <Button className={classes.button} onClick={() => this.handleStep(dialog, 'next')} disabled={dialog.containers.length === 1 || activeDialogs[dialog.key] ? activeDialogs[dialog.key] === dialog.containers.length - 1 : false}>
        {stepper && stepper.offsetWidth >= 320 ? next : null}
        <ChevronRight />
      </Button>
    }
  />
  <DialogActions className={classes.dialogActions}>
    {dialog.actions.filter(a => a.placement === 'bottom').map((action, index) => (
      this.renderDialogButton(action, index)
     ))}
  </DialogActions>
</div>
```

## Environment (optional)
Browser: Version 86.0.4240.183 (Official Build) (64-bit)
React: 16.12.0
Intro.js: 2.9.3
Intro.js-react: 0.2.0
@material-ui/core: 4.11.0

**Comment by afshinm** [comment]
@nlafleur I believe this issue is fixed now. Please install v3.1.0.

**Comment by nlafleur** [comment]
I updated Intro.js from 2.9.3 to 3.1.0 but I am still facing the same problem.

**Comment by nlafleur** [comment]
![image](https://user-images.githubusercontent.com/40174298/100989587-491a1000-3551-11eb-92a1-443cdea95930.png)
