### ISSUE TITLE
include source maps?

### ISSUE THREAD

**Issue by sumarlidason** [usablica/intro.js#1595]
## Description
Should `introjs.css.map` and other `.map` files be included in the distribution?

## Context
Recent `react-scripts` upgrade generates warning about missing `.map` file.

## Errors and Screenshots (optional)
```terminal
[w:my-gui-app] WARNING in ../../node_modules/intro.js/introjs.css (../../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!../../node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!../../node_modules/source-map-loader/dist/cjs.js!../../node_modules/intro.js/introjs.css)
[w:my-gui-app] Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
[w:my-gui-app] Failed to parse source map from '/Users/my-username/git/my-gui-app/node_modules/intro.js/introjs.css.map' file: Error: ENOENT: no such file or directory, open '/Users/my-username/git/my-gui-app/node_modules/intro.js/introjs.css.map'
[w:my-gui-app]  @ ../../node_modules/intro.js/introjs.css 8:6-225 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 61:4-74:5 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-195 83:0-195 84:22-29 84:33-47 84:50-64
[w:my-gui-app]  @ ./src/App.js 10:0-30
[w:my-gui-app]  @ ./src/index.js 8:0-24 27:37-40
[w:my-gui-app]
[w:my-gui-app] 2 warnings have detailed information that is not shown.
[w:my-gui-app] Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
[w:my-gui-app]
[w:my-gui-app] webpack 5.69.1 compiled with 2 warnings in 2772 ms
```

## Example (recommended)
```terminal
$ npm init -y
$ npm i intro.js
$ cd node_modules/intro.js
$ tree
.
├── README.md
├── intro.js
├── intro.module.js
├── introjs-rtl.css
├── introjs.css
├── license.md
├── minified
│ ├── intro.min.js
│ ├── intro.min.js.map
│ ├── introjs-rtl.min.css
│ ├── introjs-rtl.min.css.map
│ ├── introjs.min.css
│ └── introjs.min.css.map
├── package.json
└── themes
    ├── introjs-dark.css
    ├── introjs-flattener.css
    ├── introjs-modern.css
    ├── introjs-nassim.css
    ├── introjs-nazanin.css
    └── introjs-royal.css

2 directories, 19 files
```

## Environment (optional)
- Node `v16.13.2`
- NPM `8.3.0`
- macOS `12.2.1 (21D62)`
- Intro.Js `^5`
- react-scripts `^5`
- webpack `^5.69.1`
- react `^16.13.1`

**Comment by afshinm** [comment]
This is already fixed.

**Comment by flacoman91** [comment]
I am still seeing an error when running yarn start.

Failed to parse source map from '/example/react/node_modules/intro.js/intro.module.js.map' file: Error: ENOENT: no such file or directory, open '/example/react/node_modules/intro.js/intro.module.js.map'

**Comment by sumarlidason** [comment]
indeed, still broken,

```
Failed to parse source map from 'node_modules/intro.js/intro.module.js.map' file: 
  Error: ENOENT: no such file or directory, open 'node_modules/intro.js/intro.module.js.map'
Failed to parse source map from 'node_modules/intro.js/introjs.css.map' file: 
  Error: ENOENT: no such file or directory, open 'node_modules/intro.js/introjs.css.map'
```

```
% jq '.version' package.json && tree
"5.1.0"
.
├── README.md
├── intro.js
├── intro.module.js
├── introjs-rtl.css
├── introjs.css
├── license.md
├── minified
│   ├── intro.min.js
│   ├── intro.min.js.map
│   ├── introjs-rtl.min.css
│   ├── introjs-rtl.min.css.map
│   ├── introjs.min.css
│   └── introjs.min.css.map
├── package.json
└── themes
    ├── introjs-dark.css
    ├── introjs-flattener.css
    ├── introjs-modern.css
    ├── introjs-nassim.css
    ├── introjs-nazanin.css
    └── introjs-royal.css

2 directories, 19 files
```

**Comment by popuguytheparrot** [comment]
@afshinm this dont fixed. Check pls

**Comment by jisaacks** [comment]
This is now fixed. I have latest version. Getting the errors. Checked the mode_modules folder, the `.map` files are not present.

**Comment by wuhaohuang** [comment]
@afshinm indeed, still broken in V6.0.0

**Comment by fregante** [comment]
The issue isn't fixed, this can be easily verified:

- `/introjs.css` references `introjs.css.map`: https://www.unpkg.com/browse/intro.js@6.0.0/introjs.css
- `/introjs.css.map` does not exist in the package: https://www.unpkg.com/browse/intro.js@6.0.0/

**Comment by irtaza9** [comment]
Any fix for this issue?

**Comment by ddolcimascolo** [comment]
I'm in too, the react wrapper seems to work fine, though

**Comment by afshinm** [comment]
I'm going to publish 7 soon (#1886) and that should solve the issue. Although, it's interesting that I can see all the correct map files locally but unpkg doesn't have them. I will investigate.

**Comment by afshinm** [comment]
Yep, pretty sure v7 should fix that. I will publish a new version today/tomorrow.
